config/routes.rb
Rails.application.routes.draw do
	get 'profile', to: 'sessions#profile'
	post 'sessions/new', to: 'sessions#create'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/create'
	put '/gossips/:id', to: 'comments#create', as: 'salut'
	resources :gossips
	resources :comments
	resources :users
	resources :cities
	get '/team', to: 'static_pages#team'
	get '/contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name,
		presence: true,
		uniqueness: true
	validates :zip_code,
		presence: true,
		length: {in: 4..6}
	
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :gossip
	belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
		presence: true,
		length: {in: 3..14}
  validates :content,
		presence: true
	belongs_to :user
  has_many :JoinTableTagGossips
  has_many :tags, through: :JoinTableTagGossips
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  has_many :LierPrivateMessageUsers
  has_many :receivers,through: :LierPrivateMessageUsers,source: :user
  belongs_to :sender, class_name: "User"
  

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :JoinTableTagGossips
  has_many :gossips, through: :JoinTableTagGossips
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name,
		presence: true,
		length: {in: 1..25}
  validates :last_name,
		presence: true
	validates :age,
		numericality: { greater_than: 0 } 
	validates :password,
		presence: true,
		length: { minimum: 6 }
	
  belongs_to :city
  has_many :gossips
  has_many :LierPrivateMessageUsers
  has_many :received_messages,through: :LierPrivateMessageUsers, source: :private_message
  has_many :sent_messages, foreign_key: 'sender_id',class_name: "PrivateMessage"

	has_secure_password
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
		@city=City.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


  def index
  end

  def create

	if current_user != nil
	@gossip = Gossip.new(title:params[:title],content:params[:content],user:current_user) 

	else
	@gossip = Gossip.new(title:params[:title],content:params[:content],user:User.find_by(first_name:"anonymous")) 

  if @gossip.save # essaie de sauvegarder en base
		# si ça marche, il redirige vers la page d'index du site
  else
		render :error
    # sinon, il render la view new (qui est celle sur laquelle on est déjà)
  end
	end
end

  def new
  end

  def show
		@id=params[:id]
		@gossip=Gossip.find(params[:id])
  end

  def edit
  end

  def update
		@gossip=Gossip.find(params[:id])
		gossip_params = params.permit(:title, :content)
		if @gossip.update(gossip_params)
		else
			render :error_edit
		end
  end

  def destroy
		@gossip=Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
  end

	private

	def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def show
		
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
		@user=User.create(first_name:params[:first_name],last_name:params[:last_name], email:params[:email],password:params[:password], city:City.first, age:params[:age])
  
	if @user.save
	else
		render :new_user_error
	end

	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
		@user=User.create(first_name:params[:first_name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Bienvenue sur la page de création d'un nouvel utilisateur !</h1>
<h4>Remplissez les champs ci-dessous pour ouvrir un nouveau compte.</h4>

<%= form_tag(users_path, method: "post") do %>
	<%= label_tag(:first_name, "Votre prénom :") %>
	<%= text_field_tag(:first_name) %>
	<br>
	<%= label_tag(:last_name, "Votre nom :") %>
	<%= text_field_tag(:last_name) %>
	<br>
	<%= label_tag(:age, "Votre âge :") %>
	<%= text_field_tag(:age) %>
	<br>
	<%= label_tag(:email, "Votre adresse e-mail :") %>
	<%= text_field_tag(:email) %>
	<br>
	<%= label_tag(:password, "Mot de passe de votre choix :") %>
	<%= text_field_tag(:password) %>
	<br>
	<%= submit_tag("Valider") %>
<% end %>

app/views/users/new_user_error.html.erb
<h1>Bienvenue sur la page de création d'un nouvel utilisateur !</h1>
<br>
<br>
<div class="alert alert-danger" role="alert">
<% if @user.errors.any? %>
  <p>Nous n'avons pas réussi à créer votre compte utilisateur pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>
<br>


<h4>Remplissez les champs ci-dessous pour ouvrir un nouveau compte.</h4>

<%= form_tag(users_path, method: "post") do %>
	<%= label_tag(:first_name, "Votre prénom :") %>
	<%= text_field_tag(:first_name) %>
	<br>
	<%= label_tag(:last_name, "Votre nom :") %>
	<%= text_field_tag(:last_name) %>
	<br>
	<%= label_tag(:age, "Votre âge :") %>
	<%= text_field_tag(:age) %>
	<br>
	<%= label_tag(:email, "Votre adresse e-mail :") %>
	<%= text_field_tag(:email) %>
	<br>
	<%= label_tag(:password, "Mot de passe de votre choix :") %>
	<%= text_field_tag(:password) %>
	<br>
	<%= submit_tag("Valider") %>
<% end %>

app/views/users/show.html.erb
<h3>Plus d'informations sur l'utilisateur que vous avez sélectionné :</h3>


<br>
<p>Prénom : <%= @user.first_name %></p>
<p>Nom : <%= @user.last_name %></p>
<p>Age : <%= @user.age %></p>
<p>Email : <%= @user.email %></p>
<p>Description : <%= @user.description %></p>
<p>Ville : <%= @user.city.name %></p>
<br>

<p> <%= link_to "En savoir plus", city_path(@user.city.id) %> sur la ville de cet auteur </p>