config/routes.rb
Rails.application.routes.draw do
	get 'profile', to: 'sessions#profile'
	post 'sessions/new', to: 'sessions#create'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/create'
	put '/gossips/:id', to: 'comments#create', as: 'salut'
	resources :gossips
	resources :comments
	resources :users
	resources :cities
	get '/team', to: 'static_pages#team'
	get '/contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name,
		presence: true,
		uniqueness: true
	validates :zip_code,
		presence: true,
		length: {in: 4..6}
	
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :gossip
	belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
		presence: true,
		length: {in: 3..14}
  validates :content,
		presence: true
	belongs_to :user
  has_many :JoinTableTagGossips
  has_many :tags, through: :JoinTableTagGossips
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  has_many :LierPrivateMessageUsers
  has_many :receivers,through: :LierPrivateMessageUsers,source: :user
  belongs_to :sender, class_name: "User"
  

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :JoinTableTagGossips
  has_many :gossips, through: :JoinTableTagGossips
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name,
		presence: true,
		length: {in: 1..25}
  validates :last_name,
		presence: true
	validates :age,
		numericality: { greater_than: 0 } 
	validates :password,
		presence: true,
		length: { minimum: 6 }
	
  belongs_to :city
  has_many :gossips
  has_many :LierPrivateMessageUsers
  has_many :received_messages,through: :LierPrivateMessageUsers, source: :private_message
  has_many :sent_messages, foreign_key: 'sender_id',class_name: "PrivateMessage"

	has_secure_password
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
		@city=City.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


  def index
  end

  def create

	if current_user != nil
	@gossip = Gossip.new(title:params[:title],content:params[:content],user:current_user) 

	else
	@gossip = Gossip.new(title:params[:title],content:params[:content],user:User.find_by(first_name:"anonymous")) 

  if @gossip.save # essaie de sauvegarder en base
		# si ça marche, il redirige vers la page d'index du site
  else
		render :error
    # sinon, il render la view new (qui est celle sur laquelle on est déjà)
  end
	end
end

  def new
  end

  def show
		@id=params[:id]
		@gossip=Gossip.find(params[:id])
  end

  def edit
  end

  def update
		@gossip=Gossip.find(params[:id])
		gossip_params = params.permit(:title, :content)
		if @gossip.update(gossip_params)
		else
			render :error_edit
		end
  end

  def destroy
		@gossip=Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
  end

	private

	def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def show
		
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
		@user=User.create(first_name:params[:first_name],last_name:params[:last_name], email:params[:email],password:params[:password], city:City.first, age:params[:age])
  
	if @user.save
	else
		render :new_user_error
	end

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/OLDshow.html.erb
<h3>Plus d'informations sur l'utilisateur que vous avez sélectionné :</h3>


<br>
<p>Nom de la ville : <%= @city.name %></p>
<br>

<p>Les utilisateurs suivants sont associés à la même ville :</p>
<%= User.where(city_id:@city.id).each do |user| %>

<p><%= user.first_name %><%= user.last_name %></p>
<%=end%>

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/destroy.html.erb
<h1>Cities#destroy</h1>
<p>Find me in app/views/cities/destroy.html.erb</p>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/cities/show.html.erb
<h3>Plus d'informations sur la ville que vous avez sélectionnée :</h3>


<br>
<p>Nom de la ville : <%= @city.name %></p>
<br>

<p>Les potins écrits par des utilisateurs habitant cette ville sont :</p>
<%= User.where(city_id:@city.id).each do |user|%>
<%= Gossip.where(user_id:user.id).each do |gossip|%>
<p>Le potin <%= gossip.title %>, rapporté par <%="#{user.first_name} #{user.last_name}"%>, dont le contenu est : <%= gossip.content %></p>
<% end %>
<% end %>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/gossips/OLDindex.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Bienvenue sur la page d'accueil de The Gossip Project !</h1>
    <p class="lead">Le site qui recense les derniers potins croustillants</p>
  </div>
</div>
<br>
<h3>Liste des potins en magasin :</h3>
<br>
<p>(Vous pouvez, si vous le souhaitez, y aller de votre contribution et <%= link_to "ajouter un potin à la liste", new_gossip_path %>).</p>
<%= Gossip.all.each_with_index do |gossip,index| %>
<br>



<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Potin numéro <%=index+1%></h5>
<p class = "card-text">		Le potin numéro <%=index+1%> s'intitule <%=link_to "#{gossip.title}", gossip_path(gossip.id) %> et nous a été gentiment rapporté par <%=gossip.user.first_name%><%=gossip.user.first_name%>.
</p>

  </div>
</div>


<br>
<% end %>

app/views/gossips/create.html.erb
<h1>Page de création d'un nouveau potin</h1>
<br>
<div class="alert alert-success" role="alert">
  Félicitations ! Votre potin a bien été enregistré dans notre base de données.
</div>

<p>Vous pouvez retourner sur la page d'accueil en <%= link_to "cliquant ici", gossips_path%>.</p>

app/views/gossips/destroy.html.erb
<h1>Gossip#destroy</h1>
<p>Find me in app/views/gossip/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<h1>Page de modification d'un potin déjà existant</h1>
<br>
<br>
<br>
<h5>Veuillez indiquer les nouveaux champs et cliquer sur "Valider" :</h5>

<br>
<%= form_tag(gossip_path, method: "put") do %>
  <%= label_tag(:title, "Titre du potin :") %>
  <%= text_field_tag(:title) %>
  <%= label_tag(:content, "Contenu du potin :") %>
  <%= text_field_tag(:content) %>
  <%= submit_tag("Valider") %>
<% end %>

app/views/gossips/error.html.erb
<h1>Page de création d'un nouveau potin</h1>
<br>
<br>
<div class="alert alert-danger" role="alert">
<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>
<br>
<h5>Veuillez remplir les champs ci-dessous et cliquer sur "Valider" :</h5>

<br>
<%= form_tag(gossips_path, method: "post") do %>
  <%= label_tag(:title, "Titre du potin :") %>
  <%= text_field_tag(:title) %>
  <%= label_tag(:content, "Contenu du potin :") %>
  <%= text_field_tag(:content) %>
  <%= submit_tag("Valider") %>
<% end %>

app/views/gossips/error_edit.html.erb
<h1>Page de modification d'un potin existant</h1>
<br>
<br>
<div class="alert alert-danger" role="alert">
<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>
<br>
<h5>Veuillez remplir les champs ci-dessous et cliquer sur "Valider" :</h5>

<br>
<%= form_tag(gossips_path, method: "post") do %>
  <%= label_tag(:title, "Titre du potin :") %>
  <%= text_field_tag(:title) %>
  <%= label_tag(:content, "Contenu du potin :") %>
  <%= text_field_tag(:content) %>
  <%= submit_tag("Valider") %>
<% end %>

app/views/gossips/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Bienvenue sur la page d'accueil de The Gossip Project !</h1>
    <p class="lead">Le site qui recense les derniers potins croustillants</p>
  </div>
</div>
<br>
<h3>Liste des potins en magasin :</h3>
<br>
<p>(Vous pouvez, si vous le souhaitez, y aller de votre contribution et <%= link_to "ajouter un potin à la liste", new_gossip_path %>).</p>
<%= Gossip.all.each_with_index do |gossip,index| %>
<br>
<div class="list-group">
  <a class="list-group-item list-group-item-action active">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Potin numéro <%=index+1%></h5>
    </div>
    <p class="mb-1">	Le potin numéro <%=index+1%> s'intitule <%= gossip.title %> et nous a été gentiment rapporté par <%=gossip.user.first_name%> <%=gossip.user.last_name%>.</p>
  </a>
  <br>
   <br>
   <br>
  <p>En savoir plus sur <%=link_to "ce potin", gossip_path(gossip.id) %> ou bien sur la <%=link_to "ville de l'auteur de ce potin", city_path(gossip.user.city.id) %>.</p>
   <br>
   <br>

<% end %>

app/views/gossips/new.html.erb
<h1>Page de création d'un nouveau potin</h1>
<br>
<br>
<br>
<h5>Veuillez remplir les champs ci-dessous et cliquer sur "Valider" :</h5>

<br>
<%= form_tag(gossips_path, method: "post") do %>
  <%= label_tag(:title, "Titre du potin :") %>
  <%= text_field_tag(:title) %>
  <%= label_tag(:content, "Contenu du potin :") %>
  <%= text_field_tag(:content) %>
  <%= submit_tag("Valider") %>
<% end %>

app/views/gossips/show.html.erb
<h3>Plus d'informations sur le potin que vous avez sélectionné :</h3>


<br>
<p>Titre : <%= @gossip.title %></p>
<p>Contenu : <%= @gossip.content %></p>

app/views/gossips/update.html.erb
<h1>Page de modification d'un potin existant</h1>
<br>
<div class="alert alert-success" role="alert">
  Félicitations ! Votre potin a bien été modifié dans notre base de données.
</div>

<p>Vous pouvez retourner sur la page d'accueil en <%= link_to "cliquant ici", gossips_path%>.</p>

app/views/gossips/user_show.html.erb
<h3>Plus d'informations sur l'utilisateur que vous avez sélectionné :</h3>


<br>
<p>Prénom : <%= @user.first_name %></p>
<p>Nom : <%= @user.last_name %></p>
<p>Age : <%= @user.age %></p>
<p>Email : <%= @user.email %></p>
<p>Description : <%= @user.description %></p>
<p>Ville : <%= @user.city %></p>
<br>